# Generated by Django 2.1.7 on 2019-05-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PatientName', models.CharField(max_length=200)),
                ('PatientAge', models.IntegerField()),
                ('PatientID', models.IntegerField()),
                ('Allergies', models.DateField()),
                ('ChronicDisease', models.BooleanField()),
                ('History', models.TextField()),
            ],
        ),
    ]
