# Generated by Django 2.1.7 on 2019-05-11 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Allergies',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatientAge',
            field=models.DateField(),
        ),
    ]
